name = "vixy-bot"
compatibility_date = "2024-09-20"
compatibility_flags = [ "nodejs_compat" ]


[triggers]
crons = ["0 16 * * *", "0 21 * * *", "0 2 * * *"]

[vars]
DISCORD_BOT_TOKEN = ""
DISCORD_CHANNEL_ID = ""
TARGET_USER_ID=""